###SNLI + Glove.6B.100d

Determinar si una oración de premisa está implicada, es neutral o contradice una oración de hipótesis

* Pre-trained word vectors Glove 6B tokens, 400K vocab, 100d.
* Pasamos los vectores de palabras sobre la capa densa con activación 'Relu'.
* Encode the premise and hypothesis sentences using the same encoder (summation, GRU, LSTM, ...)
* Codifique las premisas e hipótesis utilizando LSTM
* Concatenar las oraciones resultantes
* 3 capas densas Relu
* softmax

In [2]:
from __future__ import print_function
from functools import reduce
import json
import os
import re
import tarfile
import tempfile
import numpy as np
import keras
import keras.backend as K
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras.layers import merge, recurrent, Dense, Input, Dropout, TimeDistributed
from keras.layers.embeddings import Embedding
from keras.layers.normalization import BatchNormalization
from keras.layers.wrappers import Bidirectional
from keras.models import Model
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer
from keras.regularizers import l2
from keras.utils import np_utils
import os, re, csv, math, codecs
from keras.layers import concatenate, Flatten, Embedding, Conv1D, MaxPooling1D, GlobalMaxPooling1D, Dropout, Dense, Activation, Input, Concatenate,Dot,RepeatVector,TimeDistributed,Multiply,Lambda,Bidirectional, LSTM, Reshape
import keras.backend as K
from keras.activations import softmax
from keras.models import Model
from keras import optimizers
from keras.activations import softmax
from keras.callbacks import EarlyStopping, History, ModelCheckpoint
np.random.seed(1337)  # for reproducibility

Using TensorFlow backend.


In [3]:
%tensorflow_version 1.15

`%tensorflow_version` only switches the major version: `1.x` or `2.x`.
You set: `1.15`. This will be interpreted as: `1.x`.


TensorFlow is already loaded. Please restart the runtime to change versions.


In [4]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
! unzip "/content/drive/My Drive/snli_1.0.zip" > /dev/null

###Funciones

In [0]:
def extract_tokens_from_binary_parse(parse):
    return parse.replace('(', ' ').replace(')', ' ').replace('-LRB-', '(').replace('-RRB-', ')').split()

In [0]:
def get_data(fn, limit=None):
  raw_data = list(yield_examples(fn=fn, limit=limit))
  left = [s1 for _, s1, s2 in raw_data]
  right = [s2 for _, s1, s2 in raw_data]
  print(max(len(x.split()) for x in left))
  print(max(len(x.split()) for x in right))

  LABELS = {'contradiction': 0, 'neutral': 1, 'entailment': 2}
  Y = np.array([LABELS[l] for l, s1, s2 in raw_data])
  Y = np_utils.to_categorical(Y, len(LABELS))

  return left, right, Y

In [0]:
def yield_examples(fn, skip_no_majority=True, limit=None):
  for i, line in enumerate(open(fn)):
    if limit and i > limit:
      break
    data = json.loads(line)
    label = data['gold_label']
    s1 = ' '.join(extract_tokens_from_binary_parse(data['sentence1_binary_parse']))
    s2 = ' '.join(extract_tokens_from_binary_parse(data['sentence2_binary_parse']))
    if skip_no_majority and label == '-':
      continue
    yield (label, s1, s2)

###Prepare data

In [0]:
to_seq = lambda X: pad_sequences(tokenizer.texts_to_sequences(X), maxlen=MAX_LEN)
prepare_data = lambda data: (to_seq(data[0]), to_seq(data[1]), data[2])

###Import Data

In [13]:
training = get_data('snli_1.0/snli_1.0_train.jsonl')
validation = get_data('snli_1.0/snli_1.0_dev.jsonl')
test = get_data('snli_1.0/snli_1.0_test.jsonl')

82
62
59
55
57
30


In [0]:
#tokenizer = Tokenizer(filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n', lower=True, split=' ', char_level=False, oov_token="UNK")
tokenizer = Tokenizer(lower=False, filters='')
tokenizer.fit_on_texts(training[0] + training[1])

In [0]:
# Lowest index from the tokenizer is 1 - we need to include 0 in our vocab count
VOCAB = len(tokenizer.word_counts) + 1
LABELS = {'contradiction': 0, 'neutral': 1, 'entailment': 2}

### Veamos algunos ejemplos


In [17]:
training[0][0]

'A person on a horse jumps over a broken down airplane .'

In [18]:
training[1][0]

'A person is training his horse for a competition .'

In [19]:
training[2][0]

array([0., 1., 0.], dtype=float32)

###Prepare dataset - Training, Validation, Test

In [0]:
MAX_LEN = 42
training = prepare_data(training)
validation = prepare_data(validation)
test = prepare_data(test)

In [0]:
  #Ejemplo de prepare

In [118]:
training[0][0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    3,   45,    8,
          2,  193,  205,   81,    2, 1171,   40,  822,    1], dtype=int32)

In [119]:
training[1][0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    3,
         45,    5, 1175,   21,  193,   38,    2,  456,    1], dtype=int32)

In [120]:
training[2][0]

array([0., 1., 0.], dtype=float32)

In [0]:
to_seq = lambda X: pad_sequences(tokenizer.texts_to_sequences(X), maxlen=MAX_LEN)

In [0]:
prepare_data = lambda data: (to_seq(data[0]), to_seq(data[1]), data[2])

In [24]:
print('Build model...')
print('Vocab size =', VOCAB)

Build model...
Vocab size = 42391


###Load Embeddings

In [32]:
#load embeddings
EMBEDDING_DIR = "/content/drive/My Drive/"
print('loading word embeddings...')
embeddings_index = {}
f = codecs.open(EMBEDDING_DIR+'glove.6B.100d.txt', encoding='utf-8')
for line in f:
    values = line.rstrip().rsplit(' ')
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()
print('found %s word vectors' % len(embeddings_index))

loading word embeddings...
found 400000 word vectors


In [0]:
EMBED_HIDDEN_SIZE = 300
# Embedding layer
embed = Embedding(VOCAB, EMBED_HIDDEN_SIZE, weights=[embedding_matrix], input_length=MAX_LEN, trainable=False)
# A dense layer applied over each sequence point
translate = TimeDistributed(Dense(SENT_HIDDEN_SIZE, activation='relu'))
# A layer to sum up the sequence of words
SumEmbeddings = keras.layers.core.Lambda(lambda x: K.sum(x, axis=1), output_shape=(SENT_HIDDEN_SIZE, ))

###Prepare embedding matrix

In [0]:
# prepare embedding matrix
embed_dim=100
embedding_matrix=np.zeros([VOCAB+4,embed_dim])
for word, idx in tokenizer.word_index.items():
  if idx <= VOCAB and word in embeddings_index:
    embedding_matrix[idx+3,:]=embeddings_index[word]

###Translate

In [26]:
SENT_HIDDEN_SIZE = 300
translate = TimeDistributed(Dense(SENT_HIDDEN_SIZE, activation='relu'))

###Premisas e Hipotesis

In [0]:
VOCAB=VOCAB+4
premise = Input(shape=(MAX_LEN,), dtype='int32')
hypothesis = Input(shape=(MAX_LEN,), dtype='int32')

prem = embed(premise)
hypo = embed(hypothesis)

prem = translate(prem)
hypo = translate(hypo)

In [0]:
value_dim=100

In [38]:
training[0].shape

(549367, 42)

###Inputs and concatenate

In [39]:
DP = 0.1
RNN = recurrent.LSTM
# RNN = lambda *args, **kwargs: Bidirectional(recurrent.LSTM(*args, **kwargs))
rnn = RNN(return_sequences=True, **rnn_kwargs)
rnn_kwargs = dict(output_dim=SENT_HIDDEN_SIZE, dropout_W=DP, dropout_U=DP)
VOCAB=VOCAB+4
# 2 pairs of input sentences
premise = Input(shape=(MAX_LEN, ), dtype='int32')
hypothesis = Input(shape=(MAX_LEN, ), dtype='int32')
# Get the word embeddings for each of these 2 pairs
prem = embed(premise)  # [batchsize, Psize, Embedsize]
hypo = embed(hypothesis) # [batchsize, Hsize, Embedsize]
# Apply the Dense layer
prem = translate(prem)
hypo = translate(hypo)
# Sum up the sequence
prem = rnn(prem)
hypo = rnn(hypo)
prem = BatchNormalization()(prem)
hypo = BatchNormalization()(hypo)

In [40]:
# Combined the 2 sentences
joint = concatenate([prem, hypo])
joint = Dropout(dropout)(joint)

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


###Capas Densas

In [0]:
L2 = 4e-6
for i in range(3):
        joint = Dense(2 * SENT_HIDDEN_SIZE, activation='relu', kernel_regularizer=l2(L2) if L2 else None)(joint)
        joint = Dropout(dropout)(joint)



###Softmax

In [0]:
pred = Dense(len(LABELS), activation='softmax')(joint)

###Model

In [0]:
model = Model(inputs=[premise, hypothesis], outputs=pred)
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [43]:
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_7 (InputLayer)            (None, 42)           0                                            
__________________________________________________________________________________________________
input_8 (InputLayer)            (None, 42)           0                                            
__________________________________________________________________________________________________
embedding_1 (Embedding)         (None, 42, 300)      12717300    input_7[0][0]                    
                                                                 input_8[0][0]                    
__________________________________________________________________________________________________
time_distributed_2 (TimeDistrib (None, 42, 300)      90300       embedding_1[2][0]          

In [46]:
from keras.callbacks import EarlyStopping, History, ModelCheckpoint
_, tmpfn = tempfile.mkstemp()
BATCH_SIZE = 512
MAX_EPOCHS = 5
# Save the best model during validation and bail out of training early if we're not improving
callbacks = [#EarlyStopping(patience=PATIENCE),
        ModelCheckpoint(tmpfn, save_best_only=True, save_weights_only=True),
        History(),
    ]
model.fit(
        [training[0], training[1]],
        training[2],
        batch_size=BATCH_SIZE,
        epochs=MAX_EPOCHS,
        validation_data=([validation[0], validation[1]], validation[2]),
        callbacks=callbacks)

Train on 549367 samples, validate on 9842 samples
Epoch 1/5
549367/549367 [==============================] - 491s 893us/step - loss: 0.6908 - acc: 0.7115 - val_loss: 0.9477 - val_acc: 0.5017
Epoch 2/5
549367/549367 [==============================] - 487s 886us/step - loss: 0.6593 - acc: 0.7286 - val_loss: 0.6234 - val_acc: 0.7495
Epoch 3/5
549367/549367 [==============================] - 492s 895us/step - loss: 0.6381 - acc: 0.7401 - val_loss: 0.6387 - val_acc: 0.7402
Epoch 4/5
549367/549367 [==============================] - 491s 894us/step - loss: 0.6214 - acc: 0.7490 - val_loss: 0.6003 - val_acc: 0.7633
Epoch 5/5
549367/549367 [==============================] - 499s 909us/step - loss: 0.6082 - acc: 0.7564 - val_loss: 0.5792 - val_acc: 0.7758


###Evaluate

In [47]:
# Restore the best found model during validation
model.load_weights(tmpfn)

loss, acc = model.evaluate([test[0], test[1]], test[2], batch_size=BATCH_SIZE)
print('Test loss / test accuracy = {:.4f} / {:.4f}'.format(loss, acc))

9824/9824 [==============================] - 4s 372us/step
Test loss / test accuracy = 0.5847 / 0.7731
